
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://root:root@db:5432/mydatabase 
    ports:
      - "4200:4200"

volumes:
  postgres_data:
 